### PR TITLE
Include baselines for TID and TEC and update baselines for TIB and TOB.

### PR DESCRIPTION
**Pull request by EmyrClement**
These are new (for TID and TEC) and updated (TIB and TOB) APV baseline text files, in relation to #cms-sw/cmssw#28081

### CODE REVIEW

**Comment by mmusich** [comment]
can please someone start the tests here? 
Thanks

**Comment by mrodozov** [comment]
please test

**Comment by mmusich** [comment]
@fabiocos, @civanch
any objection to merge this PR?
It is somewhat inconsequential on the physics output, but would be good for documentation purposes.

**Comment by fabiocos** [comment]
@mmusich I understand from the explanation above that this update is related to the already integrated cms-sw/cmssw#28081, although it was not used  in the context of that scrutiny and there was not ```external-required``` explicitly marked. From your comment I expect this does not affect standard production workflows

**Comment by fabiocos** [comment]
please test

**Comment by mmusich** [comment]
@fabiocos 
> From your comment I expect this does not affect standard production workflows.

yes, that's correct. As I said it's not strictly speaking needed for production, but this PR synchronizes the input ASCII files and the conditions in the DB (which are instead used in production).

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge

**Pull request merged**
