### PR TITLE
Add APV baselines

### PR DESCRIPTION
**Pull request by EmyrClement**
Text files containing the APV baselines relevant for cms-sw/cmssw#27823 and cms-sw/cmssw#27941

@mmusich @pieterdavid

### CODE REVIEW

**Comment by mrodozov** [comment]
@EmyrClement do you have to test with both of them at once, or one by one ?

**Comment by EmyrClement** [comment]
@mrodozov  cms-sw/cmssw#27823 requires cms-sw/cmssw#27941.  However the feature introduced by those PRs is turned off.

**Comment by mrodozov** [comment]
Meaning the data files introduced here are not used yet in the cmssw PRs ?
If yes it would be better you enable their usage to properly test the program behaviour / data files content

**Comment by mmusich** [comment]
> If yes it would be better you enable their usage to properly test the program behaviour / data files content.

@mrodozov 
Not yet. We want first to validate the feature (inactive by default) with special RelVals.
At any rate the data introduced here in production mode will be supplied via DataBase. 
These files are put here for documentation purposes and to supply a default in case the `SiStripApvSimulationParameters` content is provided by the dedicated `ESSource` introduced in https://github.com/cms-sw/cmssw/pull/27941 rather than from Global Tag.

**Comment by mrodozov** [comment]
please test

**Comment by mmusich** [comment]
@civanch @fabiocos is there any objection to merge also this one (it is related to the work done in https://github.com/cms-sw/cmssw/pull/27823 and https://github.com/cms-sw/cmssw/pull/27941 )?

**Comment by fabiocos** [comment]
@mmusich thanks for reminding me about this

**Comment by fabiocos** [comment]
+1

**Comment by fabiocos** [comment]
merge 

@civancich if we want to test the new features added in pre8 already we need these input files updated

**Comment by smuzaffar** [comment]
+externals
Only new files, cmsdist PR is https://github.com/cms-sw/cmsdist/pull/5235 which can be merged as it has been tested in this PR (and it only contains cnew files)

**Pull request merged**
